/* (C) 2021 DragonSkulle */
package org.dragonskulle.ui;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.joml.Vector4f;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueUITextRectTest {
    @Test
    public void testConstructor() {
        UITextRect actualUiTextRect = new UITextRect((UIText) null);
        UIAppearance expectedAppearance = actualUiTextRect.mAppearance;
        assertSame(expectedAppearance, actualUiTextRect.getAppearance());
        assertFalse(actualUiTextRect.isAwake());
        assertTrue(actualUiTextRect.isEnabled());
        assertNull(actualUiTextRect.getOverrideAspectRatio());
        assertFalse(actualUiTextRect.isStarted());
        assertNull(actualUiTextRect.getRectTexture());
        Vector4f colour = actualUiTextRect.getColour();
        assertEquals(1.0f, colour.w, 0.0f);
        assertSame(actualUiTextRect, actualUiTextRect.getReference().get());
        assertEquals(1.0f, colour.w(), 0.0f);
        assertEquals(1.0f, colour.y(), 0.0f);
        assertEquals(1.0f, colour.z(), 0.0f);
        assertEquals(1.0f, colour.x(), 0.0f);
    }
}
