/* (C) 2021 DragonSkulle */
package org.dragonskulle.ui;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.dragonskulle.renderer.SampledTexture;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueUIFlatImageTest {
    @Test
    public void testConstructor() {
        UIFlatImage actualUiFlatImage = new UIFlatImage(new SampledTexture("Texture Name"), true);
        assertFalse(actualUiFlatImage.isStarted());
        assertTrue(actualUiFlatImage.isEnabled());
        assertFalse(actualUiFlatImage.isAwake());
        assertSame(actualUiFlatImage, actualUiFlatImage.getReference().get());
    }

    @Test
    public void testOnDestroy() {
        UIFlatImage uiFlatImage = new UIFlatImage(new SampledTexture("Texture Name"), true);
        uiFlatImage.onDestroy();
        assertFalse(uiFlatImage.isStarted());
        assertTrue(uiFlatImage.isEnabled());
        assertFalse(uiFlatImage.isAwake());
    }
}
