/* (C) 2021 DragonSkulle */
package org.dragonskulle.ui;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.joml.Vector4f;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueUIButtonTest {
    @Test
    public void testConstructor() {
        UIButton actualUiButton = new UIButton((UIText) null);
        UIAppearance expectedAppearance = actualUiButton.mAppearance;
        assertSame(expectedAppearance, actualUiButton.getAppearance());
        assertFalse(actualUiButton.isAwake());
        assertTrue(actualUiButton.isEnabled());
        assertNull(actualUiButton.getOverrideAspectRatio());
        assertFalse(actualUiButton.isLockPressed());
        assertFalse(actualUiButton.isStarted());
        assertNull(actualUiButton.getRectTexture());
        Vector4f colour = actualUiButton.getColour();
        assertEquals(1.0f, colour.w, 0.0f);
        assertSame(actualUiButton, actualUiButton.getReference().get());
        assertEquals(1.0f, colour.x(), 0.0f);
        assertEquals(1.0f, colour.z(), 0.0f);
        assertEquals(1.0f, colour.y(), 0.0f);
        assertEquals(1.0f, colour.w(), 0.0f);
    }
}
