/* (C) 2021 DragonSkulle */
package org.dragonskulle.ui;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import org.dragonskulle.components.Component;
import org.dragonskulle.core.GameObject;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueUIManagerTest {
    @Test
    public void testUiUpdate() {
        UIManager uiManager = new UIManager();
        uiManager.uiUpdate(new ArrayList<Component>());
        assertNull(uiManager.getHoveredObject());
    }

    @Test
    public void testBuildGridUI() {
        UIManager uiManager = new UIManager();
        GameObject gameObject = new GameObject("Name");
        uiManager.buildGridUI(
                gameObject,
                1,
                10.0f,
                10.0f,
                10.0f,
                10.0f,
                new ArrayList<UIManager.IUIBuildHandler>());
        assertTrue(gameObject.isRootObject());
        assertTrue(gameObject.isEnabled());
        assertTrue(gameObject.getTransform() instanceof org.dragonskulle.components.Transform3D);
        assertEquals(0, gameObject.getDepth());
    }

    @Test
    public void testBuildVerticalUi() {
        UIManager uiManager = new UIManager();
        GameObject gameObject = new GameObject("Name");
        uiManager.buildVerticalUi(gameObject, 10.0f, 10.0f, 10.0f);
        assertTrue(gameObject.isRootObject());
        assertTrue(gameObject.isEnabled());
        assertTrue(gameObject.getTransform() instanceof org.dragonskulle.components.Transform3D);
        assertEquals(0, gameObject.getDepth());
    }

    @Test
    public void testBuildHorizontalUI() {
        UIManager uiManager = new UIManager();
        GameObject gameObject = new GameObject("Name");
        uiManager.buildHorizontalUI(gameObject, 10.0f, 10.0f, 10.0f);
        assertTrue(gameObject.isRootObject());
        assertTrue(gameObject.isEnabled());
        assertTrue(gameObject.getTransform() instanceof org.dragonskulle.components.Transform3D);
        assertEquals(0, gameObject.getDepth());
    }

    @Test
    public void testBuildWithAnchorOffset() {
        UIManager uiManager = new UIManager();
        GameObject gameObject = new GameObject("Name");
        uiManager.buildWithAnchorOffset(gameObject, 10.0f, 10.0f, 10.0f, 10.0f, 10.0f, 10.0f);
        assertTrue(gameObject.isRootObject());
        assertTrue(gameObject.isEnabled());
        assertTrue(gameObject.getTransform() instanceof org.dragonskulle.components.Transform3D);
        assertEquals(0, gameObject.getDepth());
    }

    @Test
    public void testBuildRightOf() {
        UIManager uiManager = new UIManager();
        GameObject gameObject = new GameObject("Name");
        uiManager.buildRightOf(gameObject);
        assertTrue(gameObject.isRootObject());
        assertTrue(gameObject.isEnabled());
        assertTrue(gameObject.getTransform() instanceof org.dragonskulle.components.Transform3D);
        assertEquals(0, gameObject.getDepth());
    }
}
