/* (C) 2021 DragonSkulle */
package org.dragonskulle.ui;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueUIInputBoxTest {
    @Test
    public void testConstructor() {
        UIInputBox actualUiInputBox = new UIInputBox();
        assertFalse(actualUiInputBox.isStarted());
        assertTrue(actualUiInputBox.isEnabled());
        assertFalse(actualUiInputBox.isAwake());
        assertSame(actualUiInputBox, actualUiInputBox.getReference().get());
    }

    @Test
    public void testConstructor2() {
        UIInputBox actualUiInputBox = new UIInputBox("Text");
        assertFalse(actualUiInputBox.isStarted());
        assertTrue(actualUiInputBox.isEnabled());
        assertFalse(actualUiInputBox.isAwake());
        assertSame(actualUiInputBox, actualUiInputBox.getReference().get());
    }

    @Test
    public void testFrameUpdate() {
        UIInputBox uiInputBox = new UIInputBox();
        uiInputBox.frameUpdate(0.5f);
        assertFalse(uiInputBox.isStarted());
        assertTrue(uiInputBox.isEnabled());
        assertFalse(uiInputBox.isAwake());
    }
}
