/* (C) 2021 DragonSkulle */
package org.dragonskulle.ui;

import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;

import org.dragonskulle.renderer.SampledTexture;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueUIAppearanceTest {
    @Test
    public void testSetTextFont() {
        UIAppearance uiAppearance = new UIAppearance();
        uiAppearance.setTextFont(null);
        assertNull(uiAppearance.getTextFont());
    }

    @Test
    public void testSetButtonTexture() {
        UIAppearance uiAppearance = new UIAppearance();
        SampledTexture sampledTexture = new SampledTexture("Texture Name");
        uiAppearance.setButtonTexture(sampledTexture);
        assertSame(sampledTexture, uiAppearance.getButtonTexture());
    }

    @Test
    public void testSetTextRect() {
        UIAppearance uiAppearance = new UIAppearance();
        SampledTexture sampledTexture = new SampledTexture("Texture Name");
        uiAppearance.setTextRect(sampledTexture);
        assertSame(sampledTexture, uiAppearance.getTextRectTexture());
    }

    @Test
    public void testSetTextRect2() {
        UIAppearance uiAppearance = new UIAppearance();
        uiAppearance.setTextRectTexture(null);
        SampledTexture sampledTexture = new SampledTexture("Texture Name");
        uiAppearance.setTextRect(sampledTexture);
        assertSame(sampledTexture, uiAppearance.getTextRectTexture());
    }

    @Test
    public void testSetDropDownIconTexture() {
        UIAppearance uiAppearance = new UIAppearance();
        SampledTexture sampledTexture = new SampledTexture("Texture Name");
        uiAppearance.setDropDownIconTexture(sampledTexture);
        assertSame(sampledTexture, uiAppearance.getDropDownIconTexture());
    }

    @Test
    public void testSetSliderKnobTexture() {
        UIAppearance uiAppearance = new UIAppearance();
        SampledTexture sampledTexture = new SampledTexture("Texture Name");
        uiAppearance.setSliderKnobTexture(sampledTexture);
        assertSame(sampledTexture, uiAppearance.getSliderKnobTexture());
    }

    @Test
    public void testSetRectTextures() {
        UIAppearance uiAppearance = new UIAppearance();
        SampledTexture sampledTexture = new SampledTexture("Texture Name");
        SampledTexture sampledTexture1 = new SampledTexture("Texture Name");
        SampledTexture[] sampledTextureArray =
                new SampledTexture[] {
                    sampledTexture, sampledTexture1, new SampledTexture("Texture Name")
                };
        uiAppearance.setRectTextures(sampledTextureArray);
        assertSame(sampledTextureArray, uiAppearance.getRectTextures());
    }

    @Test
    public void testFree() {
        UIAppearance uiAppearance = new UIAppearance();
        uiAppearance.free();
        assertNull(uiAppearance.getTextRectTexture());
        assertNull(uiAppearance.getTextFont());
        assertNull(uiAppearance.getSliderKnobTexture());
        assertNull(uiAppearance.getButtonTexture());
        assertNull(uiAppearance.getDropDownIconTexture());
        assertNull(uiAppearance.getRectTextures());
    }

    @Test
    public void testFree2() {
        UIAppearance uiAppearance = new UIAppearance();
        uiAppearance.setDropDownIconTexture(null);
        uiAppearance.free();
        assertNull(uiAppearance.getTextRectTexture());
        assertNull(uiAppearance.getTextFont());
        assertNull(uiAppearance.getSliderKnobTexture());
        assertNull(uiAppearance.getButtonTexture());
        assertNull(uiAppearance.getDropDownIconTexture());
        assertNull(uiAppearance.getRectTextures());
    }

    @Test
    public void testFree3() {
        UIAppearance uiAppearance = new UIAppearance();
        uiAppearance.setRectTextures(null);
        uiAppearance.free();
        assertNull(uiAppearance.getTextRectTexture());
        assertNull(uiAppearance.getTextFont());
        assertNull(uiAppearance.getSliderKnobTexture());
        assertNull(uiAppearance.getButtonTexture());
        assertNull(uiAppearance.getDropDownIconTexture());
        assertNull(uiAppearance.getRectTextures());
    }

    @Test
    public void testFree4() {
        UIAppearance uiAppearance = new UIAppearance();
        uiAppearance.setSliderKnobTexture(null);
        uiAppearance.free();
        assertNull(uiAppearance.getTextRectTexture());
        assertNull(uiAppearance.getTextFont());
        assertNull(uiAppearance.getSliderKnobTexture());
        assertNull(uiAppearance.getButtonTexture());
        assertNull(uiAppearance.getDropDownIconTexture());
        assertNull(uiAppearance.getRectTextures());
    }

    @Test
    public void testFree5() {
        UIAppearance uiAppearance = new UIAppearance();
        uiAppearance.setButtonTexture(null);
        uiAppearance.free();
        assertNull(uiAppearance.getTextRectTexture());
        assertNull(uiAppearance.getTextFont());
        assertNull(uiAppearance.getSliderKnobTexture());
        assertNull(uiAppearance.getButtonTexture());
        assertNull(uiAppearance.getDropDownIconTexture());
        assertNull(uiAppearance.getRectTextures());
    }
}
