/* (C) 2021 DragonSkulle */
package org.dragonskulle.ui;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueBuildHandlerInfoTest {

    @Test
    public void testConstructor() {
        BuildHandlerInfo actualBuildHandlerInfo = new BuildHandlerInfo(new UIDropDown(), 10.0f);
        assertFalse(actualBuildHandlerInfo.isStarted());
        assertTrue(actualBuildHandlerInfo.isEnabled());
        assertFalse(actualBuildHandlerInfo.isAwake());
        assertSame(actualBuildHandlerInfo, actualBuildHandlerInfo.getReference().get());
    }

    @Test
    public void testOnDestroy() {
        BuildHandlerInfo buildHandlerInfo = new BuildHandlerInfo(new UIDropDown(), 10.0f);
        buildHandlerInfo.onDestroy();
        assertFalse(buildHandlerInfo.isStarted());
        assertTrue(buildHandlerInfo.isEnabled());
        assertFalse(buildHandlerInfo.isAwake());
    }
}
