/* (C) 2021 DragonSkulle */
package org.dragonskulle.game;

import static org.junit.Assert.assertEquals;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueNoiseUtilTest {
    @Rule public ExpectedException thrown = ExpectedException.none();

    @Test
    public void testGetHeight() {
        assertEquals(
                93.03108f,
                NoiseUtil.getHeight(
                        1, 1, 42, new float[][] {new float[] {10.0f, 10.0f, 10.0f, 10.0f}}),
                0.0f);
    }

    @Test
    public void testGetHeight2() {
        thrown.expect(ArrayIndexOutOfBoundsException.class);
        NoiseUtil.getHeight(1, 1, 42, new float[][] {new float[] {}});
    }
}
