/* (C) 2021 DragonSkulle */
package org.dragonskulle.game;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueSpinnerTest {
    @Test
    public void testConstructor() {
        Spinner actualSpinner = new Spinner();
        assertEquals(60.0f, actualSpinner.mSpinSpeed, 0.0f);
        assertEquals(50.0f, actualSpinner.mSineSpeed, 0.0f);
        assertEquals(0.5f, actualSpinner.mSineAmplitude, 0.0f);
        assertFalse(actualSpinner.isStarted());
        assertTrue(actualSpinner.isEnabled());
        assertFalse(actualSpinner.isAwake());
        assertSame(actualSpinner, actualSpinner.getReference().get());
    }

    @Test
    public void testConstructor2() {
        Spinner actualSpinner = new Spinner(10.0f, 10.0f, 10.0f);
        assertEquals(10.0f, actualSpinner.mSpinSpeed, 0.0f);
        assertEquals(10.0f, actualSpinner.mSineSpeed, 0.0f);
        assertEquals(10.0f, actualSpinner.mSineAmplitude, 0.0f);
        assertFalse(actualSpinner.isStarted());
        assertTrue(actualSpinner.isEnabled());
        assertFalse(actualSpinner.isAwake());
        assertSame(actualSpinner, actualSpinner.getReference().get());
    }

    @Test
    public void testOnDestroy() {
        Spinner spinner = new Spinner();
        spinner.onDestroy();
        assertEquals(60.0f, spinner.mSpinSpeed, 0.0f);
        assertEquals(50.0f, spinner.mSineSpeed, 0.0f);
        assertEquals(0.5f, spinner.mSineAmplitude, 0.0f);
        assertFalse(spinner.isStarted());
        assertTrue(spinner.isEnabled());
        assertFalse(spinner.isAwake());
    }
}
