/* (C) 2021 DragonSkulle */
package org.dragonskulle.game;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.dragonskulle.core.Reference;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/
public class GameStateTest {

    @Test
    public void testOnDestroy() {
        GameState gameState = new GameState();
        gameState.onDestroy();
        assertFalse(gameState.isStarted());
        assertTrue(gameState.isInGame());
        assertTrue(gameState.isEnabled());
        assertFalse(gameState.isAwake());
    }

    @Test
    public void testRegisterGameEndListener() {
        GameState gameState = new GameState();
        gameState.registerGameEndListener(new Reference<GameState.IGameEndEvent>(null));
        assertFalse(gameState.isStarted());
        assertTrue(gameState.isInGame());
        assertTrue(gameState.isEnabled());
        assertFalse(gameState.isAwake());
    }
}
