/* (C) 2021 DragonSkulle */
package org.dragonskulle.game;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class WobblerTest {
    @Test
    public void testConstructor() {
        Wobbler actualWobbler = new Wobbler();
        assertEquals(1.0f, actualWobbler.mWobbleSpeed, 0.0f);
        assertEquals(1.0f, actualWobbler.mWobbleRange, 0.0f);
        assertFalse(actualWobbler.isStarted());
        assertTrue(actualWobbler.isEnabled());
        assertFalse(actualWobbler.isAwake());
        assertEquals(0.0f, actualWobbler.getPhaseShift(), 0.0f);
        assertSame(actualWobbler, actualWobbler.getReference().get());
    }

    @Test
    public void testConstructor2() {
        Wobbler actualWobbler = new Wobbler(10.0f, 10.0f);
        assertEquals(10.0f, actualWobbler.mWobbleSpeed, 0.0f);
        assertEquals(10.0f, actualWobbler.mWobbleRange, 0.0f);
        assertFalse(actualWobbler.isStarted());
        assertTrue(actualWobbler.isEnabled());
        assertFalse(actualWobbler.isAwake());
        assertEquals(0.0f, actualWobbler.getPhaseShift(), 0.0f);
        assertSame(actualWobbler, actualWobbler.getReference().get());
    }

    @Test
    public void testOnDestroy() {
        Wobbler wobbler = new Wobbler();
        wobbler.onDestroy();
        assertEquals(1.0f, wobbler.mWobbleSpeed, 0.0f);
        assertEquals(1.0f, wobbler.mWobbleRange, 0.0f);
        assertFalse(wobbler.isStarted());
        assertTrue(wobbler.isEnabled());
        assertFalse(wobbler.isAwake());
        assertEquals(0.0f, wobbler.getPhaseShift(), 0.0f);
    }
}
