/* (C) 2021 DragonSkulle */
package org.dragonskulle.network.components;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.dragonskulle.core.GameObject;
import org.dragonskulle.core.TemplateManager;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueClientNetworkManagerTest {
    @Test
    public void testConstructor() {
        ClientNetworkManager actualClientNetworkManager =
                new ClientNetworkManager(
                        new NetworkManager(new TemplateManager(), null),
                        "127.0.0.1",
                        8080,
                        null,
                        null,
                        null);
        assertEquals(
                ClientNetworkManager.ConnectionState.CONNECTING,
                actualClientNetworkManager.getConnectionState());
        assertEquals(0.0f, actualClientNetworkManager.getServerTime(), 0.0f);
        assertEquals(-1, actualClientNetworkManager.getNetId());
        assertTrue(
                actualClientNetworkManager.getDataOut()
                        instanceof org.dragonskulle.network.NetworkMessageStream);
    }

    @Test
    public void testGetDataOut() {
        assertTrue(
                (new ClientNetworkManager(
                                        new NetworkManager(new TemplateManager(), null),
                                        "127.0.0.1",
                                        8080,
                                        null,
                                        null,
                                        null))
                                .getDataOut()
                        instanceof org.dragonskulle.network.NetworkMessageStream);
    }

    @Test
    public void testGetNetworkObject() {
        assertNull(
                (new ClientNetworkManager(
                                new NetworkManager(new TemplateManager(), null),
                                "127.0.0.1",
                                8080,
                                null,
                                null,
                                null))
                        .getNetworkObject(123));
    }

    @Test
    public void testDisconnect() {
        ClientNetworkManager clientNetworkManager =
                new ClientNetworkManager(
                        new NetworkManager(new TemplateManager(), null),
                        "127.0.0.1",
                        8080,
                        null,
                        null,
                        null);
        clientNetworkManager.disconnect();
        assertEquals(
                ClientNetworkManager.ConnectionState.NOT_CONNECTED,
                clientNetworkManager.getConnectionState());
        assertTrue(
                clientNetworkManager.getDataOut()
                        instanceof org.dragonskulle.network.NetworkMessageStream);
    }

    @Test
    public void testDisconnect2() {
        TemplateManager templateManager = new TemplateManager();
        templateManager.addAllObjects(new GameObject("org.dragonskulle.core.GameObject"));
        ClientNetworkManager clientNetworkManager =
                new ClientNetworkManager(
                        new NetworkManager(templateManager, null),
                        "127.0.0.1",
                        8080,
                        null,
                        null,
                        null);
        clientNetworkManager.disconnect();
        assertEquals(
                ClientNetworkManager.ConnectionState.NOT_CONNECTED,
                clientNetworkManager.getConnectionState());
        assertTrue(
                clientNetworkManager.getDataOut()
                        instanceof org.dragonskulle.network.NetworkMessageStream);
    }
}
