/* (C) 2021 DragonSkulle */
package org.dragonskulle.network.components;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.joml.Vector3f;
import org.joml.Vector3fc;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueNetworkHexTransformTest {
    @Test
    public void testConstructor() {
        NetworkHexTransform actualNetworkHexTransform = new NetworkHexTransform();
        assertTrue(actualNetworkHexTransform.isSyncHeight());
        assertNull(actualNetworkHexTransform.getNetworkObject());
        assertTrue(actualNetworkHexTransform.isEnabled());
        assertFalse(actualNetworkHexTransform.isAwake());
        assertFalse(actualNetworkHexTransform.isStarted());
        assertSame(actualNetworkHexTransform, actualNetworkHexTransform.getReference().get());
        Vector3fc getResult = actualNetworkHexTransform.getAxialCoordinate().get();
        assertTrue(getResult instanceof Vector3f);
        assertEquals(0.0f, ((Vector3f) getResult).z, 0.0f);
        assertEquals(0.0f, ((Vector3f) getResult).y, 0.0f);
        assertEquals(0.0f, ((Vector3f) getResult).x, 0.0f);
    }

    @Test
    public void testOnDestroy() {
        NetworkHexTransform networkHexTransform = new NetworkHexTransform();
        networkHexTransform.onDestroy();
        assertTrue(networkHexTransform.isSyncHeight());
        assertTrue(networkHexTransform.isEnabled());
        assertFalse(networkHexTransform.isAwake());
        assertFalse(networkHexTransform.isStarted());
    }
}
