/* (C) 2021 DragonSkulle */
package org.dragonskulle.network.components.sync;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueSyncStringTest {
    @Test
    public void testSet() {
        SyncString syncString = new SyncString("Data");
        syncString.set("Data");
        assertEquals("Data", syncString.get());
        assertTrue(syncString.mDirty);
    }

    @Test
    public void testSerialize() throws IOException {
        SyncString syncString = new SyncString("Data");
        syncString.serialize(new DataOutputStream(new ByteArrayOutputStream(1)), 123);
        assertFalse(syncString.mDirty);
    }

    @Test
    public void testEquals() {
        assertFalse((new SyncString("Data")).equals("42"));
        assertFalse((new SyncString("Data")).equals(null));
    }

    @Test
    public void testHashCode() {
        assertEquals(2122729, (new SyncString("Data")).hashCode());
    }
}
