/* (C) 2021 DragonSkulle */
package org.dragonskulle.network.components.sync;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueSyncShortTest {
    @Test
    public void testSet() {
        SyncShort syncShort = new SyncShort((short) 1);
        syncShort.set((short) 1);
        assertEquals((short) 1, syncShort.get());
        assertTrue(syncShort.mDirty);
    }

    @Test
    public void testSerialize() throws IOException {
        SyncShort syncShort = new SyncShort((short) 1);
        syncShort.serialize(new DataOutputStream(new ByteArrayOutputStream(1)), 123);
        assertEquals((short) 1, syncShort.get());
        assertFalse(syncShort.mDirty);
    }

    @Test
    public void testDeserialize() throws IOException {
        SyncShort syncShort = new SyncShort((short) 1);
        syncShort.deserialize(
                new DataInputStream(
                        new ByteArrayInputStream("AAAAAAAAAAAAAAAAAAAAAAAA".getBytes("UTF-8"))));
        assertEquals((short) 16705, syncShort.get());
    }

    @Test
    public void testEquals() {
        assertFalse((new SyncShort((short) 1)).equals("42"));
        assertFalse((new SyncShort((short) 1)).equals(null));
    }

    @Test
    public void testHashCode() {
        assertEquals(1, (new SyncShort((short) 1)).hashCode());
    }
}
