/* (C) 2021 DragonSkulle */
package org.dragonskulle.network.components.sync;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueSyncLongTest {
    @Test
    public void testSet() {
        SyncLong syncLong = new SyncLong(1L);
        syncLong.set(1L);
        assertEquals(1L, syncLong.get());
        assertTrue(syncLong.mDirty);
    }

    @Test
    public void testSerialize() throws IOException {
        SyncLong syncLong = new SyncLong(1L);
        syncLong.serialize(new DataOutputStream(new ByteArrayOutputStream(1)), 123);
        assertEquals(1L, syncLong.get());
        assertFalse(syncLong.mDirty);
    }

    @Test
    public void testDeserialize() throws IOException {
        SyncLong syncLong = new SyncLong(1L);
        syncLong.deserialize(
                new DataInputStream(
                        new ByteArrayInputStream("AAAAAAAAAAAAAAAAAAAAAAAA".getBytes("UTF-8"))));
        assertEquals(4702111234474983745L, syncLong.get());
    }

    @Test
    public void testEquals() {
        assertFalse((new SyncLong(1L)).equals("42"));
        assertFalse((new SyncLong(1L)).equals(null));
    }

    @Test
    public void testHashCode() {
        assertEquals(Integer.SIZE, (new SyncLong(1L)).hashCode());
    }
}
