/* (C) 2021 DragonSkulle */
package org.dragonskulle.network.components.sync;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import org.joml.Vector3f;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueSyncVector3Test {
    @Test
    public void testSerialize() throws IOException {
        SyncVector3 syncVector3 = new SyncVector3();
        syncVector3.serialize(new DataOutputStream(new ByteArrayOutputStream(1)), 123);
        assertFalse(syncVector3.mDirty);
    }

    @Test
    public void testDeserialize() throws IOException {
        SyncVector3 syncVector3 = new SyncVector3();
        syncVector3.deserialize(
                new DataInputStream(
                        new ByteArrayInputStream("AAAAAAAAAAAAAAAAAAAAAAAA".getBytes("UTF-8"))));
        assertEquals(12.078431f, ((Vector3f) syncVector3.get()).z, 0.0f);
        assertEquals(12.078431f, ((Vector3f) syncVector3.get()).y, 0.0f);
        assertEquals(12.078431f, ((Vector3f) syncVector3.get()).x, 0.0f);
    }

    @Test
    public void testConstructor() {
        assertTrue((new SyncVector3()).get() instanceof org.joml.Vector3f);
    }

    @Test
    public void testConstructor2() {
        Vector3f vector3f = new Vector3f(10.0f);
        assertSame(vector3f, (new SyncVector3(vector3f)).get());
    }

    @Test
    public void testSet() {
        SyncVector3 syncVector3 = new SyncVector3();
        syncVector3.set(new Vector3f(10.0f));
        assertTrue(syncVector3.mDirty);
        assertEquals(10.0f, ((Vector3f) syncVector3.get()).z, 0.0f);
        assertEquals(10.0f, ((Vector3f) syncVector3.get()).y, 0.0f);
        assertEquals(10.0f, ((Vector3f) syncVector3.get()).x, 0.0f);
    }
}
