/* (C) 2021 DragonSkulle */
package org.dragonskulle.network.components.sync;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueSyncBoolTest {
    @Test
    public void testSet() {
        SyncBool syncBool = new SyncBool(true);
        syncBool.set(true);
        assertTrue(syncBool.get());
        assertTrue(syncBool.mDirty);
    }

    @Test
    public void testSerialize() throws IOException {
        SyncBool syncBool = new SyncBool(true);
        syncBool.serialize(new DataOutputStream(new ByteArrayOutputStream(1)), 123);
        assertTrue(syncBool.get());
        assertFalse(syncBool.mDirty);
    }

    @Test
    public void testDeserialize() throws IOException {
        SyncBool syncBool = new SyncBool(true);
        syncBool.deserialize(
                new DataInputStream(
                        new ByteArrayInputStream("AAAAAAAAAAAAAAAAAAAAAAAA".getBytes("UTF-8"))));
        assertTrue(syncBool.get());
    }

    @Test
    public void testEquals() {
        assertFalse((new SyncBool(true)).equals("42"));
        assertFalse((new SyncBool(true)).equals(null));
    }

    @Test
    public void testHashCode() {
        assertEquals(1262, (new SyncBool(true)).hashCode());
    }
}
