/* (C) 2021 DragonSkulle */
package org.dragonskulle.utils;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueTextUtilsTest {
    @Test
    public void testPadAfter() {
        assertEquals("Input", TextUtils.padAfter("Input", 3));
        assertNull(TextUtils.padAfter(null, 3));
        assertEquals("42 ", TextUtils.padAfter("42", 3));
        assertEquals("Input", TextUtils.padAfter("Input", 0));
    }

    @Test
    public void testPadBefore() {
        assertEquals("Input", TextUtils.padBefore("Input", 3));
        assertNull(TextUtils.padBefore(null, 3));
        assertEquals(" 42", TextUtils.padBefore("42", 3));
        assertEquals("Input", TextUtils.padBefore("Input", 0));
    }

    @Test
    public void testConstructField() {
        assertEquals("Name: 42", TextUtils.constructField("Name", 42, 3));
        assertEquals("Name: 42", TextUtils.constructField("Name", "42", 3));
        assertEquals("Name: null", TextUtils.constructField("Name", (String) null, 3));
    }
}
