/* (C) 2021 DragonSkulle */
package org.dragonskulle.utils;

import static org.junit.Assert.assertEquals;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueIOUtilsTest {
    @Rule public ExpectedException thrown = ExpectedException.none();

    @Test
    public void testReadNBytes() throws IOException {
        byte[] actualReadNBytesResult =
                IOUtils.readNBytes(
                        new ByteArrayInputStream("AAAAAAAAAAAAAAAAAAAAAAAA".getBytes("UTF-8")), 3);
        assertEquals(3, actualReadNBytesResult.length);
        assertEquals('A', actualReadNBytesResult[0]);
        assertEquals('A', actualReadNBytesResult[1]);
        assertEquals('A', actualReadNBytesResult[2]);
    }

    @Test
    public void testReadNBytes2() throws IOException {
        assertEquals(0, IOUtils.readNBytes(new ByteArrayInputStream(new byte[] {}), 3).length);
    }

    @Test
    public void testReadNBytes4() throws IOException {
        thrown.expect(IllegalArgumentException.class);
        IOUtils.readNBytes(
                new ByteArrayInputStream("AAAAAAAAAAAAAAAAAAAAAAAA".getBytes("UTF-8")), -1);
    }
}
