/* (C) 2021 DragonSkulle */
package org.dragonskulle.utils;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueMathUtilsTest {
    @Test
    public void testLerp() {
        assertEquals(10.0f, MathUtils.lerp(10.0f, 10.0f, 10.0f), 0.0f);
    }

    @Test
    public void testClamp() {
        assertEquals(10.0f, MathUtils.clamp(10.0f, 10.0f, 10.0f), 0.0f);
    }

    @Test
    public void testLog() {
        assertEquals(Integer.MAX_VALUE, MathUtils.log(42, 1));
    }

    @Test
    public void testRoundDownToPow2() {
        assertEquals(1, MathUtils.roundDownToPow2(1));
    }

    @Test
    public void testRoundStep() {
        assertEquals(10.0f, MathUtils.roundStep(10.0f, 10.0f), 0.0f);
    }

    @Test
    public void testMapOneRangeToAnother() {
        assertEquals(0.0, MathUtils.mapOneRangeToAnother(10.0, 10.0, 10.0, 10.0, 10.0, 1), 0.0);
    }

    @Test
    public void testNormalise() {
        assertEquals(0.0f, MathUtils.normalise(10.0f, 10.0f, 10.0f), 0.0f);
    }
}
