/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.misc;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class ArcPathTest {
    @Test
    public void testSetObjGap() {
        ArcPath arcPath = new ArcPath();
        arcPath.setObjGap(10.0f);
        assertEquals(10.0f, arcPath.getObjGap(), 0.0f);
    }

    @Test
    public void testSetSpawnStart() {
        ArcPath arcPath = new ArcPath();
        arcPath.setSpawnStart(10.0f);
        assertEquals(10.0f, arcPath.getSpawnStart(), 0.0f);
    }

    @Test
    public void testSetSpawnEnd() {
        ArcPath arcPath = new ArcPath();
        arcPath.setSpawnEnd(10.0f);
        assertEquals(10.0f, arcPath.getSpawnEnd(), 0.0f);
    }

    @Test
    public void testOnDestroy() {
        ArcPath arcPath = new ArcPath();
        arcPath.onDestroy();
        assertEquals(1.0f, arcPath.getAmplitude(), 0.0f);
        assertFalse(arcPath.isStarted());
        assertTrue(arcPath.isEnabled());
        assertFalse(arcPath.isAwake());
        assertEquals(0.0f, arcPath.getSpawnStart(), 0.0f);
        assertEquals(0.0f, arcPath.getSpawnOffset(), 0.0f);
        assertEquals(1.0f, arcPath.getSpawnEnd(), 0.0f);
        assertEquals(0.1f, arcPath.getObjGap(), 0.0f);
    }
}
