/* (C) 2021 DragonSkulle */
package org.dragonskulle.input;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueBindingTest {
    @Test
    public void testConstructor() {
        Binding actualBinding = new Binding(1);
        assertTrue(actualBinding.getActions().isEmpty());
        assertEquals(1, actualBinding.getButton());
    }

    @Test
    public void testConstructor2() {
        Binding actualBinding = new Binding(1, new ArrayList<Action>());
        assertTrue(actualBinding.getActions().isEmpty());
        assertEquals(1, actualBinding.getButton());
    }

    @Test
    public void testConstructor3() {
        Action action = new Action("Name");
        Action action1 = new Action("Name");
        Binding actualBinding = new Binding(1, action, action1, new Action("Name"));
        assertEquals(3, actualBinding.getActions().size());
        assertEquals(1, actualBinding.getButton());
    }

    @Test
    public void testConstructor4() {
        Action action = new Action("Name");
        Binding actualBinding = new Binding(1, null, action, new Action("Name"));
        assertEquals(2, actualBinding.getActions().size());
        assertEquals(1, actualBinding.getButton());
    }

    @Test
    public void testSetButton() {
        Binding binding = new Binding(1);
        binding.setButton(1);
        assertEquals(1, binding.getButton());
    }

    @Test
    public void testAddAction() {
        Binding binding = new Binding(1);
        binding.addAction(new Action("Name"));
        assertEquals(1, binding.getActions().size());
    }

    @Test
    public void testAddAction2() {
        Binding binding = new Binding(1);
        binding.addAction(null);
        assertTrue(binding.getActions().isEmpty());
        assertEquals(1, binding.getButton());
    }

    @Test
    public void testAddActions() {
        Binding binding = new Binding(1);
        binding.addActions(new ArrayList<Action>());
        assertTrue(binding.getActions().isEmpty());
    }

    @Test
    public void testAddActions2() {
        Binding binding = new Binding(1);
        Action action = new Action("Name");
        Action action1 = new Action("Name");
        binding.addActions(action, action1, new Action("Name"));
        assertEquals(3, binding.getActions().size());
    }

    @Test
    public void testAddActions3() {
        Binding binding = new Binding(1);
        Action action = new Action("Name");
        binding.addActions(null, action, new Action("Name"));
        assertEquals(2, binding.getActions().size());
    }
}
