/* (C) 2021 DragonSkulle */
package org.dragonskulle.input;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.joml.Vector2f;
import org.joml.Vector2fc;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueCursorTest {
    @Test
    public void testConstructor() {
        Cursor actualCursor = new Cursor();
        Vector2fc rawPosition = actualCursor.getRawPosition();
        assertTrue(rawPosition instanceof Vector2f);
        Vector2fc position = actualCursor.getPosition();
        assertTrue(position instanceof Vector2f);
        assertEquals(0.0f, ((Vector2f) position).x, 0.0f);
        assertEquals(0.0f, position.y(), 0.0f);
        assertEquals(0.0f, ((Vector2f) rawPosition).x, 0.0f);
        assertEquals(0.0f, rawPosition.y(), 0.0f);
    }

    @Test
    public void testSetPosition() {
        Cursor cursor = new Cursor();
        cursor.setPosition(10.0f, 10.0f);
        Vector2fc rawPosition = cursor.getRawPosition();
        assertEquals(10.0f, ((Vector2f) rawPosition).x, 0.0f);
        assertEquals(10.0f, rawPosition.y(), 0.0f);
    }

    @Test
    public void testStartDrag() {
        Cursor cursor = new Cursor();
        cursor.startDrag();
        assertEquals(0.0f, cursor.getDragAngle(), 0.0f);
        assertEquals(0.0f, cursor.getDragDistance(), 0.0f);
    }

    @Test
    public void testEndDrag() {
        Cursor cursor = new Cursor();
        cursor.endDrag();
        assertEquals(0.0f, cursor.getDragAngle(), 0.0f);
    }

    @Test
    public void testInDrag() {
        assertFalse((new Cursor()).inDrag());
    }

    @Test
    public void testHadLittleDrag() {
        assertFalse((new Cursor()).hadLittleDrag());
    }

    @Test
    public void testGetDragStart() {
        assertNull((new Cursor()).getDragStart());
    }

    @Test
    public void testGetDragAngle() {
        assertEquals(0.0f, (new Cursor()).getDragAngle(), 0.0f);
    }

    @Test
    public void testGetDragDistance() {
        assertEquals(0.0f, (new Cursor()).getDragDistance(), 0.0f);
    }
}
