/* (C) 2021 DragonSkulle */
package org.dragonskulle.input;

import static org.junit.Assert.assertFalse;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueButtonsTest {
    @Test
    public void testIsPressed() {
        assertFalse((new Buttons(new Bindings())).isPressed(1));
    }
}
