/* (C) 2021 DragonSkulle */
package org.dragonskulle.input;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueActionsTest {
    @Test
    public void testGetOnPress() {
        assertNull(Actions.getOnPress());
    }

    @Test
    public void testGetOnRelease() {
        assertNull(Actions.getOnRelease());
    }

    @Test
    public void testGetOnChar() {
        assertNull(Actions.getOnChar());
    }

    @Test
    public void testIsBeingIntercepted() {
        assertFalse(Actions.isBeingIntercepted());
    }
}
