/* (C) 2021 DragonSkulle */
package org.dragonskulle.input;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueBindingsTest {
    @Test
    public void testGetActions() {
        assertTrue((new Bindings()).getActions().isEmpty());
        assertTrue((new Bindings()).getActions(1).isEmpty());
    }

    @Test
    public void testGetActions2() {
        Bindings bindings = new Bindings();
        bindings.addBinding(1, new Action("Name"));
        assertEquals(1, bindings.getActions(1).size());
    }

    @Test
    public void testGetButtons() {
        Bindings bindings = new Bindings();
        assertTrue(bindings.getButtons(new Action("Name")).isEmpty());
    }
}
