/* (C) 2021 DragonSkulle */
package org.dragonskulle.core.futures;

import static org.junit.Assert.assertSame;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueAwaitFutureTest {
    @Test
    public void testConstructor() {
        AwaitFuture actualAwaitFuture = new AwaitFuture(null);
        assertSame(actualAwaitFuture, actualAwaitFuture.getRoot());
    }

    @Test
    public void testConstructor2() {
        AwaitFuture awaitFuture = new AwaitFuture(null);
        assertSame(awaitFuture, (new AwaitFuture(awaitFuture, null)).getRoot());
    }
}
