/* (C) 2021 DragonSkulle */
package org.dragonskulle.core.futures;

import static org.junit.Assert.assertSame;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueThenFutureTest {
    @Test
    public void testConstructor() {
        AwaitFuture awaitFuture = new AwaitFuture(null);
        assertSame(awaitFuture, (new ThenFuture(awaitFuture, null)).getRoot());
    }

    @Test
    public void testConstructor2() {
        ThenFuture actualThenFuture = new ThenFuture(null);
        assertSame(actualThenFuture, actualThenFuture.getRoot());
    }
}
