/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ai.algorithms.graphs;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueNodeTest {
    @Test
    public void testConstructor() {
        Node actualNode = new Node(1, null);
        assertTrue(actualNode.getConnections().isEmpty());
        assertEquals(1, actualNode.getNodeId());
        assertNull(actualNode.getHexTile().get());
    }

    @Test
    public void testAddConnection() {
        Node node = new Node(1, null);
        node.addConnection(2, 3);
        ArrayList<Connection> connections = node.getConnections();
        assertEquals(1, connections.size());
        Connection getResult = connections.get(0);
        assertEquals(3, getResult.getWeight());
        assertEquals(1, getResult.getOriginNode());
        assertEquals(2, getResult.getDestinationNode());
    }
}
