/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ai.algorithms.graphs;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.util.HashMap;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueGraphTest {
    @Test
    public void testAddNode() {
        Graph graph = new Graph();
        graph.addNode(123, null);
        HashMap<Integer, Node> integerNodeMap = graph.mGraph;
        assertEquals(1, integerNodeMap.size());
        Node getResult = integerNodeMap.get(123);
        assertTrue(getResult.getConnections().isEmpty());
        assertEquals(123, getResult.getNodeId());
        assertNull(getResult.getHexTile().get());
    }

    @Test
    public void testGetConnection() {
        assertTrue((new Graph()).getConnection(10).isEmpty());
    }

    @Test
    public void testGetNodeHeuristic() {
        assertEquals(Integer.MAX_VALUE, (new Graph()).getNodeHeuristic(1));
    }

    @Test
    public void testGetNode() {
        assertNull((new Graph()).getNode(1));
    }
}
