/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ai.algorithms;

import static org.junit.Assert.assertTrue;

import java.util.Deque;
import org.dragonskulle.game.player.ai.algorithms.graphs.Graph;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class AStarTest {
    @Test
    public void testConstructor() {
        Deque<Integer> path = (new AStar(new Graph(), 1, 3)).getPath();
        assertTrue(path instanceof java.util.ArrayDeque);
        assertTrue(path.isEmpty());
    }
}
