/* (C) 2021 DragonSkulle */
package org.dragonskulle.devtools;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueRenderDebugTest {
    @Test
    public void testFrameUpdate() {
        RenderDebug renderDebug = new RenderDebug();
        renderDebug.frameUpdate(0.5f);
        assertFalse(renderDebug.isStarted());
        assertTrue(renderDebug.isEnabled());
        assertFalse(renderDebug.isAwake());
    }

    @Test
    public void testOnDestroy() {
        RenderDebug renderDebug = new RenderDebug();
        renderDebug.onDestroy();
        assertFalse(renderDebug.isStarted());
        assertTrue(renderDebug.isEnabled());
        assertFalse(renderDebug.isAwake());
    }
}
