/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.lobby;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.dragonskulle.core.TemplateManager;
import org.dragonskulle.network.components.NetworkManager;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueLobbyTest {
    @Test
    public void testCreateServer() {
        NetworkManager networkManager = new NetworkManager(new TemplateManager(), null);
        networkManager.createClient("127.0.0.1", 8080, null, null, null);
        Lobby.createServer(networkManager, null);
        assertFalse(networkManager.isStarted());
        assertTrue(networkManager.isClient());
        assertTrue(networkManager.isEnabled());
        assertFalse(networkManager.isAwake());
    }
}
