/* (C) 2021 DragonSkulle */
package org.dragonskulle.core;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.dragonskulle.audio.components.AudioListener;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueSceneTest {
    @Test
    public void testFindRootObject2() {
        Scene scene = new Scene("Name");
        GameObject gameObject = new GameObject("Name");
        scene.addRootObject(gameObject);
        assertSame(gameObject, scene.findRootObject("Name"));
    }

    @Test
    public void testFindRootObject4() {
        Scene scene = new Scene("Name");
        scene.addRootObject(new GameObject("org.dragonskulle.components.Transform"));
        GameObject gameObject = new GameObject("Name");
        scene.addRootObject(gameObject);
        assertSame(gameObject, scene.findRootObject("Name"));
    }

    @Test
    public void testRegisterSingleton() {
        Scene scene = new Scene("Name");
        scene.registerSingleton(new AudioListener());
        assertTrue(Reference.isValid(scene.getSingletonRef(AudioListener.class)));
    }

    @Test
    public void testUnregisterSingleton() {
        Scene scene = new Scene("Name");
        scene.registerSingleton(new AudioListener());
        assertTrue(Reference.isValid(scene.getSingletonRef(AudioListener.class)));
        scene.unregisterSingleton(AudioListener.class);
        assertFalse(Reference.isValid(scene.getSingletonRef(AudioListener.class)));
    }
}
