/* (C) 2021 DragonSkulle */
package org.dragonskulle.core;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueResourceTest {
    @Test
    public void testFree() {
        Resource<Object> resource = new Resource<Object>(null);
        resource.free();
        assertNull(resource.get());
    }

    @Test
    public void testClone() {
        Resource<Object> resource =
                new Resource<Object>(
                        new ResourceManager.CountedResource<Object>(
                                new ResourceArguments<Object, Object>(
                                        Object.class, "Name", "Additional Args"),
                                "Resource"));
        assertEquals(resource, resource.clone());
    }
}
