/* (C) 2021 DragonSkulle */
package org.dragonskulle.core;

import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.dragonskulle.audio.components.AudioListener;
import org.dragonskulle.components.Component;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueSingletonStoreTest {
    @Test
    public void testRegister() {
        SingletonStore singletonStore = new SingletonStore();
        assertTrue(singletonStore.register(new AudioListener()));
    }

    @Test
    public void testGet() {
        SingletonStore singletonStore = new SingletonStore();
        assertNull(singletonStore.<Component>get(Component.class));
    }

    @Test
    public void testGetRef() {
        SingletonStore singletonStore = new SingletonStore();
        assertNull(singletonStore.<Component>getRef(Component.class));
    }

    @Test
    public void testUnregister() {
        SingletonStore singletonStore = new SingletonStore();
        assertNull(singletonStore.unregister(Object.class));
    }
}
