/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.map;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class ClientFogTileHeightTest {
    @Test
    public void testLateFrameUpdate() {
        ClientFogTileHeight clientFogTileHeight = new ClientFogTileHeight();
        clientFogTileHeight.lateFrameUpdate(0.5f);
        assertFalse(clientFogTileHeight.isStarted());
        assertTrue(clientFogTileHeight.isEnabled());
        assertFalse(clientFogTileHeight.isAwake());
    }

    @Test
    public void testOnDestroy() {
        ClientFogTileHeight clientFogTileHeight = new ClientFogTileHeight();
        clientFogTileHeight.onDestroy();
        assertFalse(clientFogTileHeight.isStarted());
        assertTrue(clientFogTileHeight.isEnabled());
        assertFalse(clientFogTileHeight.isAwake());
    }
}
