/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueFadeTileTest {
    @Test
    public void testSetState() {
        FadeTile fadeTile = new FadeTile();
        fadeTile.setState(true, 10.0f);
        assertEquals(10.0f, fadeTile.getTargetHeight(), 0.0f);
    }

    @Test
    public void testSetState2() {
        FadeTile fadeTile = new FadeTile();
        fadeTile.setState(false, 10.0f);
        assertEquals(10.0f, fadeTile.getTargetHeight(), 0.0f);
    }

    @Test
    public void testFrameUpdate() {
        FadeTile fadeTile = new FadeTile();
        fadeTile.frameUpdate(0.5f);
        assertEquals("", fadeTile.getChildName());
        assertFalse(fadeTile.isStarted());
        assertTrue(fadeTile.isEnabled());
        assertFalse(fadeTile.isDestroyOnFadeOut());
        assertFalse(fadeTile.isAwake());
        assertEquals(0.0f, fadeTile.getTargetHeight(), 0.0f);
        assertEquals(0.4f, fadeTile.getFadeTime(), 0.0f);
        assertEquals(1.0f, fadeTile.getFadeValue(), 0.0f);
    }

    @Test
    public void testOnDestroy() {
        FadeTile fadeTile = new FadeTile();
        fadeTile.onDestroy();
        assertEquals("", fadeTile.getChildName());
        assertFalse(fadeTile.isStarted());
        assertTrue(fadeTile.isEnabled());
        assertFalse(fadeTile.isDestroyOnFadeOut());
        assertFalse(fadeTile.isAwake());
        assertEquals(0.0f, fadeTile.getTargetHeight(), 0.0f);
        assertEquals(0.4f, fadeTile.getFadeTime(), 0.0f);
        assertEquals(1.0f, fadeTile.getFadeValue(), 0.0f);
    }
}
