/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class HeightControllerTest {

    @Test
    public void testFrameUpdate() {
        HeightController heightController = new HeightController();
        heightController.frameUpdate(0.5f);
        assertFalse(heightController.isStarted());
        assertTrue(heightController.isEnabled());
        assertFalse(heightController.isAwake());
        assertEquals(0.0f, heightController.getTargetHeight(), 0.0f);
        assertEquals(3.0f, heightController.getSpeed(), 0.0f);
    }

    @Test
    public void testOnDestroy() {
        HeightController heightController = new HeightController();
        heightController.onDestroy();
        assertFalse(heightController.isStarted());
        assertTrue(heightController.isEnabled());
        assertFalse(heightController.isAwake());
        assertEquals(0.0f, heightController.getTargetHeight(), 0.0f);
        assertEquals(3.0f, heightController.getSpeed(), 0.0f);
    }
}
