/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import java.util.LinkedList;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class HexagonMapTest {
    @Test
    public void testFloodFill() {
        HexagonMap hexagonMap = new HexagonMap();
        hexagonMap.floodFill(new LinkedList<HexagonTile>(), null);
        assertFalse(hexagonMap.isStarted());
        assertTrue(hexagonMap.isEnabled());
        assertFalse(hexagonMap.isAwake());
        assertEquals(51, hexagonMap.getSize());
    }

    @Test
    public void testGetTilesInRadius() {
        HexagonMap hexagonMap = new HexagonMap();
        assertTrue(hexagonMap.getTilesInRadius(null, 1, 3, new ArrayList<HexagonTile>()).isEmpty());
    }

    @Test
    public void testGetTilesInRadius2() {
        HexagonMap hexagonMap = new HexagonMap();
        assertTrue(
                hexagonMap.getTilesInRadius(null, 1, true, new ArrayList<HexagonTile>()).isEmpty());
    }

    @Test
    public void testGetTilesInRadius3() {
        HexagonMap hexagonMap = new HexagonMap();
        assertTrue(
                hexagonMap
                        .getTilesInRadius(null, 1, false, new ArrayList<HexagonTile>())
                        .isEmpty());
    }

    @Test
    public void testOnDestroy() {
        HexagonMap hexagonMap = new HexagonMap();
        hexagonMap.onDestroy();
        assertFalse(hexagonMap.isStarted());
        assertTrue(hexagonMap.isEnabled());
        assertFalse(hexagonMap.isAwake());
        assertEquals(51, hexagonMap.getSize());
    }
}
