/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class HexagonTileTest {
    @Test
    public void testTileTypeGetTile() {
        assertNull(HexagonTile.TileType.getTile((byte) 'A'));
        assertEquals(HexagonTile.TileType.LAND, HexagonTile.TileType.getTile((byte) 0));
    }
}
