/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.map;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.dragonskulle.core.GameObject;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class HexagonTileStoreTest {
    @Test
    public void testGetViewedTileMask() {
        assertEquals(
                0, (new HexagonTileStore(0, 42, new HexagonMap())).getViewedTileMask(1).length);
    }

    @Test
    public void testConstructor() {
        HexagonMap hexagonMap = new HexagonMap();
        new HexagonTileStore(0, 42, hexagonMap);
        assertNull(hexagonMap.getGameObject());
        assertFalse(hexagonMap.isStarted());
        assertTrue(hexagonMap.isEnabled());
        assertFalse(hexagonMap.isAwake());
        assertEquals(51, hexagonMap.getSize());
        assertNull(hexagonMap.getNetworkObject());
        assertNull(hexagonMap.getNetworkManager());
    }

    @Test
    public void testGetTile() {
        assertNull((new HexagonTileStore(0, 42, new HexagonMap())).getTile(1, 1));
        assertNull((new HexagonTileStore(0, 42, new HexagonMap())).getTile(-1, 1));
        assertNull((new HexagonTileStore(0, 42, new HexagonMap())).getTile(1, -1));
    }

    @Test
    public void testTileToStoreActionsGetNetworkManager() {
        assertNull(
                ((new HexagonTileStore(0, 42, new HexagonMap())).new TileToStoreActions())
                        .getNetworkManager());
    }

    @Test
    public void testTileToStoreActionsGetNetworkManager2() {
        HexagonMap hexagonMap = new HexagonMap();
        hexagonMap.setGameObject(new GameObject("Name"));
        assertNull(
                ((new HexagonTileStore(0, 42, hexagonMap)).new TileToStoreActions())
                        .getNetworkManager());
    }
}
