service: rest-api

provider:
  name: aws
  runtime: nodejs6.10 # set node.js runtime
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  stage: ${opt:stage, 'v1'}
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  region: eu-central-1

functions: 
  create:
    handler: handler.create 
    events:
      - http:
          path: hosts 
          method: post
          cors: true
  getOne:
    handler: handler.getOne 
    events:
     - http:
         path: hosts/{id}
         method: get
         cors: true

  getAll:
    handler: handler.getAll 
    events:
     - http:
         path: hosts
         method: get
         cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: hosts/{id}
         method: delete
         cors: true

plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation