/* (C) 2021 DragonSkulle */
package org.dragonskulle.audio.components;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueAudioSourceTest {
    @Test
    public void testDetachSource() {
        AudioSource audioSource = new AudioSource();
        audioSource.detachSource();
        assertFalse(audioSource.isStarted());
        assertTrue(audioSource.isEnabled());
        assertFalse(audioSource.isAwake());
        assertEquals(1.0f, audioSource.getVolume(), 0.0f);
        assertEquals(-1.0f, audioSource.getTimeLeft(), 0.0f);
        assertEquals(50000.0f, audioSource.getRadius(), 0.0f);
        assertEquals(0, audioSource.getLooping());
        assertEquals(1.0f, audioSource.getPitch(), 0.0f);
    }

    @Test
    public void testSetVolume() {
        AudioSource audioSource = new AudioSource();
        audioSource.setVolume(10.0f);
        assertEquals(1.0f, audioSource.getVolume(), 0.0f);
    }

    @Test
    public void testSetLooping() {
        AudioSource audioSource = new AudioSource();
        audioSource.setLooping(true);
        assertEquals(1, audioSource.getLooping());
    }

    @Test
    public void testSetLooping2() {
        AudioSource audioSource = new AudioSource();
        audioSource.setLooping(false);
        assertEquals(0, audioSource.getLooping());
    }

    @Test
    public void testSetPitch() {
        AudioSource audioSource = new AudioSource();
        audioSource.setPitch(10.0f);
        assertEquals(1.0f, audioSource.getPitch(), 0.0f);
    }

    @Test
    public void testSetRadius() {
        AudioSource audioSource = new AudioSource();
        audioSource.setRadius(10.0f);
        assertEquals(10.0f, audioSource.getRadius(), 0.0f);
    }

    @Test
    public void testOnDestroy() {
        AudioSource audioSource = new AudioSource();
        audioSource.onDestroy();
        assertNull(audioSource.getSound());
    }

    @Test
    public void testFixedUpdate() {
        AudioSource audioSource = new AudioSource();
        audioSource.fixedUpdate(0.5f);
        assertFalse(audioSource.isStarted());
        assertTrue(audioSource.isEnabled());
        assertFalse(audioSource.isAwake());
        assertEquals(1.0f, audioSource.getVolume(), 0.0f);
        assertEquals(-1.0f, audioSource.getTimeLeft(), 0.0f);
        assertEquals(50000.0f, audioSource.getRadius(), 0.0f);
        assertEquals(0, audioSource.getLooping());
        assertEquals(1.0f, audioSource.getPitch(), 0.0f);
    }
}
