/* (C) 2021 DragonSkulle */
package org.dragonskulle.audio.components;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueAudioListenerTest {
    @Test
    public void testOnDestroy() {
        AudioListener audioListener = new AudioListener();
        audioListener.onDestroy();
        assertFalse(audioListener.isStarted());
        assertTrue(audioListener.isEnabled());
        assertFalse(audioListener.isAwake());
    }
}
