/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.building.stat;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueStatTypeTest {
    @Rule public ExpectedException thrown = ExpectedException.none();

    @Test
    public void testFromNiceName2() {
        assertEquals(StatType.ATTACK, StatType.fromNiceName("ATTACK"));
    }

    @Test
    public void testGetFromID() {
        assertEquals(StatType.BUILD_DISTANCE, StatType.getFromID(1));
        assertNull(StatType.getFromID(123));
        assertNull(StatType.getFromID(-1));
    }

    @Test
    public void testGetFromID2() {
        thrown.expect(ArrayIndexOutOfBoundsException.class);
        StatType.getFromID(6);
    }

    @Test
    public void testGetNiceName() {
        assertEquals("ATTACK", StatType.ATTACK.getNiceName());
    }
}
