/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.camera;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueTargetMovementTest {

    @Test
    public void testFrameUpdate() {
        TargetMovement targetMovement = new TargetMovement();
        targetMovement.frameUpdate(0.5f);
        assertFalse(targetMovement.isStarted());
        assertEquals(0.1f, targetMovement.getEndDelta(), 0.0f);
        assertEquals(0.1f, targetMovement.getHoldTime(), 0.0f);
        assertEquals(10.0f, targetMovement.getSpeed(), 0.0f);
        assertEquals(90.0f, targetMovement.getMaxMoveSpeed(), 0.0f);
        assertFalse(targetMovement.isAwake());
        assertEquals(10.0f, targetMovement.getMaxSpeedDistance(), 0.0f);
        assertTrue(targetMovement.isEnabled());
        assertEquals(10.0f, targetMovement.getMinMoveSpeed(), 0.0f);
    }

    @Test
    public void testOnDestroy() {
        TargetMovement targetMovement = new TargetMovement();
        targetMovement.onDestroy();
        assertFalse(targetMovement.isStarted());
        assertEquals(0.1f, targetMovement.getEndDelta(), 0.0f);
        assertEquals(0.1f, targetMovement.getHoldTime(), 0.0f);
        assertEquals(10.0f, targetMovement.getSpeed(), 0.0f);
        assertEquals(90.0f, targetMovement.getMaxMoveSpeed(), 0.0f);
        assertFalse(targetMovement.isAwake());
        assertEquals(10.0f, targetMovement.getMaxSpeedDistance(), 0.0f);
        assertTrue(targetMovement.isEnabled());
        assertEquals(10.0f, targetMovement.getMinMoveSpeed(), 0.0f);
    }
}
