/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.camera;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueDragMovementTest {
    @Test
    public void testFrameUpdate() {
        DragMovement dragMovement = new DragMovement();
        dragMovement.frameUpdate(0.5f);
        assertFalse(dragMovement.isStarted());
        assertTrue(dragMovement.isEnabled());
        assertFalse(dragMovement.isAwake());
    }

    @Test
    public void testOnDestroy() {
        DragMovement dragMovement = new DragMovement();
        dragMovement.onDestroy();
        assertFalse(dragMovement.isStarted());
        assertTrue(dragMovement.isEnabled());
        assertFalse(dragMovement.isAwake());
    }
}
