/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.camera;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class KeyboardMovementTest {
    @Test
    public void testFrameUpdate() {
        KeyboardMovement keyboardMovement = new KeyboardMovement();
        keyboardMovement.frameUpdate(0.5f);
        assertFalse(keyboardMovement.isStarted());
        assertTrue(keyboardMovement.isEnabled());
        assertFalse(keyboardMovement.isAwake());
        assertEquals(0.0f, keyboardMovement.getZoomLevel(), 0.0f);
        assertEquals(180.0f, keyboardMovement.getRotateSpeed(), 0.0f);
        assertEquals(5.0f, keyboardMovement.getMinMoveSpeed(), 0.0f);
        assertEquals(90.0f, keyboardMovement.getMaxMoveSpeed(), 0.0f);
    }

    @Test
    public void testOnDestroy() {
        KeyboardMovement keyboardMovement = new KeyboardMovement();
        keyboardMovement.onDestroy();
        assertFalse(keyboardMovement.isStarted());
        assertTrue(keyboardMovement.isEnabled());
        assertFalse(keyboardMovement.isAwake());
        assertEquals(0.0f, keyboardMovement.getZoomLevel(), 0.0f);
        assertEquals(180.0f, keyboardMovement.getRotateSpeed(), 0.0f);
        assertEquals(5.0f, keyboardMovement.getMinMoveSpeed(), 0.0f);
        assertEquals(90.0f, keyboardMovement.getMaxMoveSpeed(), 0.0f);
    }
}
