/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.camera;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class ZoomTiltTest {

    @Test
    public void testFrameUpdate() {
        ZoomTilt zoomTilt = new ZoomTilt();
        zoomTilt.frameUpdate(0.5f);
        assertFalse(zoomTilt.isStarted());
        assertTrue(zoomTilt.isEnabled());
        assertFalse(zoomTilt.isAwake());
        assertEquals(0.0f, zoomTilt.getZoomLevel(), 0.0f);
        assertEquals(-30.0f, zoomTilt.getMinTilt(), 0.0f);
        assertEquals(-75.0f, zoomTilt.getMaxTilt(), 0.0f);
    }

    @Test
    public void testOnDestroy() {
        ZoomTilt zoomTilt = new ZoomTilt();
        zoomTilt.onDestroy();
        assertFalse(zoomTilt.isStarted());
        assertTrue(zoomTilt.isEnabled());
        assertFalse(zoomTilt.isAwake());
        assertEquals(0.0f, zoomTilt.getZoomLevel(), 0.0f);
        assertEquals(-30.0f, zoomTilt.getMinTilt(), 0.0f);
        assertEquals(-75.0f, zoomTilt.getMaxTilt(), 0.0f);
    }
}
