/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBluePredefinedBuildingsTest {
    @Test
    public void testGetPurchasable() {
        assertTrue(PredefinedBuildings.getPurchasable(1).isEmpty());
        assertEquals(1, PredefinedBuildings.getPurchasable(20).size());
    }

}
