/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class PredefinedBuildingsTest {
    @Test
    public void testGetPurchasable() {
        assertTrue(PredefinedBuildings.getPurchasable(1).isEmpty());
        assertEquals(1, PredefinedBuildings.getPurchasable(20).size());
    }

    @Test
    public void testGetIndex() {
        assertEquals(
                -1,
                PredefinedBuildings.getIndex(
                        new BuildingDescriptor(1, 1, 1, 1, 1, "M Icon Path", "M Name")));
    }
}
