/* (C) 2021 DragonSkulle */
package org.dragonskulle.network;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueNetworkClientTest {
    @Test
    public void testGetDataOut() {
        assertTrue(
                (new NetworkClient("127.0.0.1", 8080, null)).getDataOut()
                        instanceof NetworkMessageStream);
    }

    @Test
    public void testConstructor() {
        NetworkClient actualNetworkClient = new NetworkClient("127.0.0.1", 8080, null);
        assertTrue(actualNetworkClient.isConnected());
        assertEquals(0.0f, actualNetworkClient.getSimLatency(), 0.0f);
    }

    @Test
    public void testDispose() {
        NetworkClient networkClient = new NetworkClient("127.0.0.1", 8080, null);
        networkClient.dispose();
        assertTrue(networkClient.getDataOut() instanceof NetworkMessageStream);
        assertFalse(networkClient.isConnected());
    }

    @Test
    public void testProcessAllRequests() {
        assertEquals(0, (new NetworkClient("127.0.0.1", 8080, null)).processAllRequests());
    }

    @Test
    public void testProcessRequests() {
        assertEquals(0, (new NetworkClient("127.0.0.1", 8080, null)).processRequests());
        assertEquals(0, (new NetworkClient("Ip", 18, null)).processRequests());
    }

    @Test
    public void testProcessGameRequests() {
        assertEquals(0, (new NetworkClient("127.0.0.1", 8080, null)).processGameRequests());
    }

    @Test
    public void testProcessGameRequests2() {
        NetworkClient networkClient = new NetworkClient("127.0.0.1", 8080, null);
        networkClient.setSimLatency(10.0f);
        assertEquals(0, networkClient.processGameRequests());
    }
}
