/* (C) 2021 DragonSkulle */
package org.dragonskulle.network;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueNetworkMessageTest {
    @Test
    public void testToByteArray() {
        assertEquals(0, NetworkMessage.toByteArray(new ArrayList<Byte>()).length);
    }

    @Test
    public void testToByteArray2() {
        ArrayList arrayList = new ArrayList();
        arrayList.add((byte) 'A');
        arrayList.add((byte) 'A');
        arrayList.add((byte) 'A');
        arrayList.add((byte) 'A');
        arrayList.add((byte) 'A');
        arrayList.add((byte) 'A');
        arrayList.add((byte) 'A');
        arrayList.add((byte) 'A');
        arrayList.add((byte) 'A');
        byte[] actualToByteArrayResult = NetworkMessage.toByteArray(arrayList);
        assertEquals(9, actualToByteArrayResult.length);
        assertEquals('A', actualToByteArrayResult[0]);
        assertEquals('A', actualToByteArrayResult[1]);
        assertEquals('A', actualToByteArrayResult[2]);
        assertEquals('A', actualToByteArrayResult[3]);
        assertEquals('A', actualToByteArrayResult[4]);
        assertEquals('A', actualToByteArrayResult[5]);
        assertEquals('A', actualToByteArrayResult[6]);
        assertEquals('A', actualToByteArrayResult[7]);
        assertEquals('A', actualToByteArrayResult[8]);
    }

    @Test
    public void testMaskSizeInBytes() {
        assertEquals(3, NetworkMessage.maskSizeInBytes(3));
    }

    @Test
    public void testGetMaskFromBytes() throws UnsupportedEncodingException {
        boolean[] actualMaskFromBytes =
                NetworkMessage.getMaskFromBytes("AAAAAAAA".getBytes("UTF-8"));
        assertEquals(8, actualMaskFromBytes.length);
        assertTrue(actualMaskFromBytes[0]);
        assertTrue(actualMaskFromBytes[1]);
        assertTrue(actualMaskFromBytes[2]);
        assertTrue(actualMaskFromBytes[3]);
        assertTrue(actualMaskFromBytes[4]);
        assertTrue(actualMaskFromBytes[5]);
        assertTrue(actualMaskFromBytes[6]);
        assertTrue(actualMaskFromBytes[7]);
    }

    @Test
    public void testGetMaskFromBytes2() {
        boolean[] actualMaskFromBytes =
                NetworkMessage.getMaskFromBytes(new byte[] {0, 'A', 'A', 'A', 'A', 'A', 'A', 'A'});
        assertEquals(8, actualMaskFromBytes.length);
        assertFalse(actualMaskFromBytes[0]);
        assertTrue(actualMaskFromBytes[1]);
        assertTrue(actualMaskFromBytes[2]);
        assertTrue(actualMaskFromBytes[3]);
        assertTrue(actualMaskFromBytes[4]);
        assertTrue(actualMaskFromBytes[5]);
        assertTrue(actualMaskFromBytes[6]);
        assertTrue(actualMaskFromBytes[7]);
    }

    @Test
    public void testConvertBoolArrayToBytes() {
        byte[] actualConvertBoolArrayToBytesResult =
                NetworkMessage.convertBoolArrayToBytes(new boolean[] {true, true, true, true});
        assertEquals(4, actualConvertBoolArrayToBytesResult.length);
        assertEquals((byte) 1, actualConvertBoolArrayToBytesResult[0]);
        assertEquals((byte) 1, actualConvertBoolArrayToBytesResult[1]);
        assertEquals((byte) 1, actualConvertBoolArrayToBytesResult[2]);
        assertEquals((byte) 1, actualConvertBoolArrayToBytesResult[3]);
    }

    @Test
    public void testConvertBoolArrayToBytes2() {
        byte[] actualConvertBoolArrayToBytesResult =
                NetworkMessage.convertBoolArrayToBytes(new boolean[] {false, true, true, true});
        assertEquals(4, actualConvertBoolArrayToBytesResult.length);
        assertEquals((byte) 0, actualConvertBoolArrayToBytesResult[0]);
        assertEquals((byte) 1, actualConvertBoolArrayToBytesResult[1]);
        assertEquals((byte) 1, actualConvertBoolArrayToBytesResult[2]);
        assertEquals((byte) 1, actualConvertBoolArrayToBytesResult[3]);
    }

    @Test
    public void testConvertCollectionMaskToBytes() {
        assertEquals(
                0, NetworkMessage.convertCollectionMaskToBytes(new ArrayList<Boolean>()).length);
    }

    @Test
    public void testConvertCollectionMaskToBytes2() {
        ArrayList<Boolean> resultBooleanList = new ArrayList<Boolean>();
        resultBooleanList.add(true);
        byte[] actualConvertCollectionMaskToBytesResult =
                NetworkMessage.convertCollectionMaskToBytes(resultBooleanList);
        assertEquals(1, actualConvertCollectionMaskToBytesResult.length);
        assertEquals((byte) 1, actualConvertCollectionMaskToBytesResult[0]);
    }

    @Test
    public void testConvertCollectionMaskToBytes3() {
        ArrayList<Boolean> resultBooleanList = new ArrayList<Boolean>();
        resultBooleanList.add(false);
        byte[] actualConvertCollectionMaskToBytesResult =
                NetworkMessage.convertCollectionMaskToBytes(resultBooleanList);
        assertEquals(1, actualConvertCollectionMaskToBytesResult.length);
        assertEquals((byte) 0, actualConvertCollectionMaskToBytesResult[0]);
    }
}
