/* (C) 2021 DragonSkulle */
package org.dragonskulle.network;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueUPnPTest {
    @Test
    public void testGetExternalIPAddress() {
        assertNull(UPnP.getExternalIPAddress());
    }

    @Test
    public void testAddPortMapping() {
        assertFalse(UPnP.addPortMapping(8080, "Protocol"));
    }

    @Test
    public void testDeletePortMapping() {
        assertFalse(UPnP.deletePortMapping(8080, "Protocol"));
    }

    @Test
    public void testIsPortAvailable() {
        assertFalse(UPnP.isPortAvailable(8080, "Protocol"));
    }
}
