/* (C) 2021 DragonSkulle */
package org.dragonskulle.renderer;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueBindingDescriptionTest {
    @Test
    public void testInstanced() {
        BindingDescription actualInstancedResult = BindingDescription.instanced(3);
        assertEquals(1, actualInstancedResult.mBindingId);
        assertEquals(3, actualInstancedResult.mSize);
        assertEquals(1, actualInstancedResult.mInputRate);
    }

    @Test
    public void testInstancedWithMatrix() {
        BindingDescription actualInstancedWithMatrixResult =
                BindingDescription.instancedWithMatrix(3);
        assertEquals(1, actualInstancedWithMatrixResult.mBindingId);
        assertEquals(67, actualInstancedWithMatrixResult.mSize);
        assertEquals(1, actualInstancedWithMatrixResult.mInputRate);
    }

    @Test
    public void testInstancedWithMatrixAndLights() {
        BindingDescription actualInstancedWithMatrixAndLightsResult =
                BindingDescription.instancedWithMatrixAndLights(3, 3);
        assertEquals(1, actualInstancedWithMatrixAndLightsResult.mBindingId);
        assertEquals(139, actualInstancedWithMatrixAndLightsResult.mSize);
        assertEquals(1, actualInstancedWithMatrixAndLightsResult.mInputRate);
    }
}
