/* (C) 2021 DragonSkulle */
package org.dragonskulle.renderer;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import java.util.List;
import org.dragonskulle.renderer.components.Light;
import org.dragonskulle.renderer.components.Renderable;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueDrawCallStateTest {
    @Test
    public void testDrawDataEndDrawData() {
        DrawCallState.DrawData drawData = new DrawCallState.DrawData();
        drawData.endDrawData(1, 1L);
        assertEquals(1, drawData.getDescriptorSets().length);
    }

    @Test
    public void testDrawDataEndDrawData2() {
        DrawCallState.DrawData drawData = new DrawCallState.DrawData();
        drawData.endDrawData(0, 1L);
        assertEquals(1, drawData.getDescriptorSets().length);
    }

    @Test
    public void testDrawDataUpdateInstanceBuffer() {
        DrawCallState.DrawData drawData = new DrawCallState.DrawData();
        ShaderSet shaderSet = new ShaderSet();
        drawData.updateInstanceBuffer(shaderSet, null, new ArrayList<Light>());
        assertEquals(0, shaderSet.getFragmentPushConstantSize());
        assertFalse(shaderSet.isVertexUniformDataDirty());
        assertFalse(shaderSet.isPreSort());
        assertFalse(shaderSet.isGeometryUniformDataDirty());
        assertFalse(shaderSet.isFragmentUniformDataDirty());
        assertTrue(shaderSet.isDepthTest());
        assertFalse(shaderSet.isAlphaBlend());
        assertEquals(0, shaderSet.getVertexUniformDataSize());
        assertEquals(0, shaderSet.getVertexAttributeDescriptions().length);
        assertEquals(1000, shaderSet.getRenderOrder());
        assertEquals(0, shaderSet.getNumFragmentTextures());
        assertEquals(0, shaderSet.getLightCount());
        assertEquals(0, shaderSet.getGeometryUniformDataSize());
        assertEquals(0, shaderSet.getFragmentUniformDataSize());
        List<Renderable> expectedObjects = drawData.mObjects;
        assertSame(expectedObjects, drawData.getObjects());
        assertEquals(0, drawData.getInstanceBufferOffset());
    }
}
