/* (C) 2021 DragonSkulle */
package org.dragonskulle.renderer;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueTextureMappingTest {
    @Test
    public void testConstructor() {
        TextureMapping actualTextureMapping = new TextureMapping();
        assertEquals(TextureMapping.TextureFiltering.LINEAR, actualTextureMapping.mFiltering);
        assertEquals(TextureMapping.TextureWrapping.CLAMP, actualTextureMapping.mWrapW);
        assertEquals(TextureMapping.TextureWrapping.CLAMP, actualTextureMapping.mWrapV);
        assertEquals(TextureMapping.TextureWrapping.CLAMP, actualTextureMapping.mWrapU);
    }

    @Test
    public void testConstructor2() {
        TextureMapping actualTextureMapping =
                new TextureMapping(TextureMapping.TextureFiltering.NEAREST);
        assertEquals(TextureMapping.TextureFiltering.NEAREST, actualTextureMapping.mFiltering);
        assertEquals(TextureMapping.TextureWrapping.CLAMP, actualTextureMapping.mWrapW);
        assertEquals(TextureMapping.TextureWrapping.CLAMP, actualTextureMapping.mWrapV);
        assertEquals(TextureMapping.TextureWrapping.CLAMP, actualTextureMapping.mWrapU);
    }

    @Test
    public void testTextureFilteringFromGLTF() {
        assertEquals(
                TextureMapping.TextureFiltering.LINEAR,
                TextureMapping.TextureFiltering.fromGLTF(42));
        assertEquals(
                TextureMapping.TextureFiltering.LINEAR,
                TextureMapping.TextureFiltering.fromGLTF(null));
        assertEquals(
                TextureMapping.TextureFiltering.NEAREST,
                TextureMapping.TextureFiltering.fromGLTF(9728));
    }

    @Test
    public void testTextureWrappingFromGLTF() {
        assertEquals(
                TextureMapping.TextureWrapping.CLAMP, TextureMapping.TextureWrapping.fromGLTF(42));
        assertEquals(
                TextureMapping.TextureWrapping.REPEAT,
                TextureMapping.TextureWrapping.fromGLTF(null));
        assertEquals(
                TextureMapping.TextureWrapping.REPEAT,
                TextureMapping.TextureWrapping.fromGLTF(10497));
        assertEquals(
                TextureMapping.TextureWrapping.MIRROR,
                TextureMapping.TextureWrapping.fromGLTF(33648));
    }

    @Test
    public void testHashCode() {
        assertEquals(2221, (new TextureMapping()).hashCode());
    }

    @Test
    public void testEquals() {
        assertFalse((new TextureMapping()).equals("42"));
    }

    @Test
    public void testEquals2() {
        TextureMapping textureMapping = new TextureMapping();
        assertTrue(textureMapping.equals(new TextureMapping()));
    }

    @Test
    public void testEquals3() {
        TextureMapping textureMapping = new TextureMapping();
        assertFalse(
                textureMapping.equals(new TextureMapping(TextureMapping.TextureFiltering.NEAREST)));
    }
}
