/* (C) 2021 DragonSkulle */
package org.dragonskulle.renderer;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueVulkanShaderDescriptorPoolTest {
    @Test
    public void testGetDescriptorSet() {
        assertEquals(0L, (new VulkanShaderDescriptorPool()).getDescriptorSet(1));
    }
}
