/* (C) 2021 DragonSkulle */
package org.dragonskulle.renderer;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueTextureTest {

    @Test
    public void testFree() {
        Texture texture = new Texture();
        texture.free();
        assertEquals(0, texture.getWidth());
        assertEquals(0, texture.getHeight());
        assertEquals(0, texture.getChannels());
    }
}
