/* (C) 2021 DragonSkulle */
package org.dragonskulle.renderer;

import static org.junit.Assert.assertEquals;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueAttributeDescriptionTest {
    @Rule public ExpectedException thrown = ExpectedException.none();

    @Test
    public void testWithMatrix() {
        assertEquals(
                5, AttributeDescription.withMatrix(new AttributeDescription(123, 1, 1, 2)).length);
        assertEquals(4, AttributeDescription.withMatrix().length);
    }

    @Test
    public void testWithLights() {
        assertEquals(
                7,
                AttributeDescription.withLights(3, new AttributeDescription(123, 1, 1, 2)).length);
        assertEquals(6, AttributeDescription.withLights(3).length);
    }

    @Test
    public void testWithLights2() {
        thrown.expect(NegativeArraySizeException.class);
        AttributeDescription.withLights(-1, new AttributeDescription(123, 1, 1, 2));
    }

    @Test
    public void testWithLights3() {
        AttributeDescription attributeDescription = new AttributeDescription(123, 1, 1, 2);
        thrown.expect(ArrayIndexOutOfBoundsException.class);
        AttributeDescription.withLights(
                -1, attributeDescription, new AttributeDescription(123, 1, 1, 2));
    }
}
