/* (C) 2021 DragonSkulle */
package org.dragonskulle.renderer;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueFontTest {

    @Test
    public void testFree() {
        Font font = new Font();
        font.free();
        assertEquals(0, font.getWidth());
        assertEquals(Font.LINE_HEIGHT, font.getNextLineOffset());
        assertEquals(0, font.getHeight());
        assertEquals(0, font.getChannels());
    }
}
