/* (C) 2021 DragonSkulle */
package org.dragonskulle.renderer;

import static org.junit.Assert.assertFalse;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBluePhysicalDeviceTest {
    @Test
    public void testQueueFamilyIndicesIsComplete() {
        assertFalse((new PhysicalDevice.QueueFamilyIndices()).isComplete());
    }
}
