/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ui;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueUIBuildingOptionsTest {
    @Test
    public void testConstructor() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        UIBuildingOptions actualUiBuildingOptions = new UIBuildingOptions(uiShopSection);
        assertFalse(actualUiBuildingOptions.isStarted());
        assertTrue(actualUiBuildingOptions.isEnabled());
        assertFalse(actualUiBuildingOptions.isAwake());
        assertEquals(0, actualUiBuildingOptions.getTokens());
        assertSame(uiShopSection, actualUiBuildingOptions.getParent());
        assertSame(actualUiBuildingOptions, actualUiBuildingOptions.getReference().get());
    }

    @Test
    public void testOnDestroy() {
        UIBuildingOptions uiBuildingOptions =
                new UIBuildingOptions(
                        new UIShopSection(
                                new UIMenuLeftDrawer(null, null, null, null, null, null)));
        uiBuildingOptions.onDestroy();
        assertFalse(uiBuildingOptions.isStarted());
        assertTrue(uiBuildingOptions.isEnabled());
        assertFalse(uiBuildingOptions.isAwake());
        assertEquals(0, uiBuildingOptions.getTokens());
    }
}
