/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ui;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueUITokenCounterTest {

    @Test
    public void testOnDestroy() {
        UITokenCounter uiTokenCounter = new UITokenCounter();
        uiTokenCounter.onDestroy();
        assertFalse(uiTokenCounter.isStarted());
        assertTrue(uiTokenCounter.isEnabled());
        assertFalse(uiTokenCounter.isAwake());
    }

    @Test
    public void testFixedUpdate() {
        UITokenCounter uiTokenCounter = new UITokenCounter();
        uiTokenCounter.fixedUpdate(0.5f);
        assertFalse(uiTokenCounter.isStarted());
        assertTrue(uiTokenCounter.isEnabled());
        assertFalse(uiTokenCounter.isAwake());
    }
}
