/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ui;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueUIBuildingUpgradeTest {
    @Test
    public void testConstructor() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        UIBuildingUpgrade actualUiBuildingUpgrade = new UIBuildingUpgrade(uiShopSection);
        assertEquals(-1, actualUiBuildingUpgrade.getBuildingStatUpdateCount());
        assertFalse(actualUiBuildingUpgrade.isStarted());
        assertTrue(actualUiBuildingUpgrade.isEnabled());
        assertFalse(actualUiBuildingUpgrade.isAwake());
        assertSame(uiShopSection, actualUiBuildingUpgrade.getParent());
        assertSame(actualUiBuildingUpgrade, actualUiBuildingUpgrade.getReference().get());
    }

    @Test
    public void testOnDestroy() {
        UIBuildingUpgrade uiBuildingUpgrade =
                new UIBuildingUpgrade(
                        new UIShopSection(
                                new UIMenuLeftDrawer(null, null, null, null, null, null)));
        uiBuildingUpgrade.onDestroy();
        assertEquals(-1, uiBuildingUpgrade.getBuildingStatUpdateCount());
        assertFalse(uiBuildingUpgrade.isStarted());
        assertTrue(uiBuildingUpgrade.isEnabled());
        assertFalse(uiBuildingUpgrade.isAwake());
    }

    @Test
    public void testFixedUpdate() {
        UIBuildingUpgrade uiBuildingUpgrade =
                new UIBuildingUpgrade(
                        new UIShopSection(
                                new UIMenuLeftDrawer(null, null, null, null, null, null)));
        uiBuildingUpgrade.fixedUpdate(0.5f);
        assertEquals(-1, uiBuildingUpgrade.getBuildingStatUpdateCount());
        assertFalse(uiBuildingUpgrade.isStarted());
        assertTrue(uiBuildingUpgrade.isEnabled());
        assertFalse(uiBuildingUpgrade.isAwake());
    }

    @Test
    public void testFixedUpdate2() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        uiShopSection.markDidBuild(true);
        UIBuildingUpgrade uiBuildingUpgrade = new UIBuildingUpgrade(uiShopSection);
        uiBuildingUpgrade.fixedUpdate(0.5f);
        assertEquals(-1, uiBuildingUpgrade.getBuildingStatUpdateCount());
        assertFalse(uiBuildingUpgrade.isStarted());
        assertTrue(uiBuildingUpgrade.isEnabled());
        assertFalse(uiBuildingUpgrade.isAwake());
    }
}
