/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ui;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class UIDescriptionTest {
    @Test
    public void testOnDestroy() {
        UIDescription uiDescription = new UIDescription();
        uiDescription.onDestroy();
        assertFalse(uiDescription.isStarted());
        assertTrue(uiDescription.isEnabled());
        assertFalse(uiDescription.isAwake());
    }
}
