/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ui;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class UILinkedScrollBarTest {
    @Test
    public void testFrameUpdate() {
        UILinkedScrollBar uiLinkedScrollBar = new UILinkedScrollBar();
        uiLinkedScrollBar.frameUpdate(0.5f);
        assertFalse(uiLinkedScrollBar.isStarted());
        assertTrue(uiLinkedScrollBar.isEnabled());
        assertFalse(uiLinkedScrollBar.isAwake());
    }

    @Test
    public void testOnDestroy() {
        UILinkedScrollBar uiLinkedScrollBar = new UILinkedScrollBar();
        uiLinkedScrollBar.onDestroy();
        assertFalse(uiLinkedScrollBar.isStarted());
        assertTrue(uiLinkedScrollBar.isEnabled());
        assertFalse(uiLinkedScrollBar.isAwake());
    }
}
