/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ui;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.dragonskulle.core.GameObject;
import org.dragonskulle.core.TemplateManager;
import org.dragonskulle.network.components.NetworkManager;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class UIPauseMenuTest {
    @Test
    public void testConstructor() {
        NetworkManager networkManager = new NetworkManager(new TemplateManager(), null);
        UIPauseMenu actualUiPauseMenu = new UIPauseMenu(networkManager, new GameObject("Name"));
        assertFalse(actualUiPauseMenu.isStarted());
        assertTrue(actualUiPauseMenu.isEnabled());
        assertFalse(actualUiPauseMenu.isAwake());
        assertSame(actualUiPauseMenu, actualUiPauseMenu.getReference().get());
    }

    @Test
    public void testOnDestroy() {
        NetworkManager networkManager = new NetworkManager(new TemplateManager(), null);
        UIPauseMenu uiPauseMenu = new UIPauseMenu(networkManager, new GameObject("Name"));
        uiPauseMenu.onDestroy();
        assertFalse(uiPauseMenu.isStarted());
        assertFalse(uiPauseMenu.isPaused());
        assertTrue(uiPauseMenu.isEnabled());
        assertFalse(uiPauseMenu.isAwake());
    }
}
