/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ui;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class UISettingsMenuTest {
    @Test
    public void testConstructor() {
        UISettingsMenu actualUiSettingsMenu = new UISettingsMenu(null);
        assertFalse(actualUiSettingsMenu.isStarted());
        assertTrue(actualUiSettingsMenu.isEnabled());
        assertFalse(actualUiSettingsMenu.isAwake());
        assertSame(actualUiSettingsMenu, actualUiSettingsMenu.getReference().get());
    }

    @Test
    public void testFrameUpdate() {
        UISettingsMenu uiSettingsMenu = new UISettingsMenu(null);
        uiSettingsMenu.frameUpdate(0.5f);
        assertFalse(uiSettingsMenu.isStarted());
        assertTrue(uiSettingsMenu.isEnabled());
        assertFalse(uiSettingsMenu.isAwake());
    }

    @Test
    public void testOnDestroy() {
        UISettingsMenu uiSettingsMenu = new UISettingsMenu(null);
        uiSettingsMenu.onDestroy();
        assertFalse(uiSettingsMenu.isStarted());
        assertTrue(uiSettingsMenu.isEnabled());
        assertFalse(uiSettingsMenu.isAwake());
    }
}
