/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.player.ui;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import org.dragonskulle.core.GameObject;
import org.dragonskulle.core.Reference;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class UIShopSectionTest {
    @Test
    public void testConstructor() {
        UIShopSection actualUiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        assertFalse(actualUiShopSection.isStarted());
        assertFalse(actualUiShopSection.isAwake());
        assertTrue(actualUiShopSection.isEnabled());
        assertEquals(UIShopSection.ShopState.CLOSED, actualUiShopSection.getLastState());
        assertEquals(UIShopSection.ShopState.MY_BUILDING_SELECTED, actualUiShopSection.getState());
        assertNull(actualUiShopSection.getParent().mNotifyScreenChange);
        assertNull(actualUiShopSection.getCurrentPanel().get());
        assertSame(actualUiShopSection, actualUiShopSection.getReference().get());
    }

    @Test
    public void testOnDestroy() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        uiShopSection.onDestroy();
        assertFalse(uiShopSection.isStarted());
        assertFalse(uiShopSection.isAwake());
        assertTrue(uiShopSection.isEnabled());
        assertEquals(UIShopSection.ShopState.CLOSED, uiShopSection.getLastState());
        assertEquals(UIShopSection.ShopState.MY_BUILDING_SELECTED, uiShopSection.getState());
    }

    @Test
    public void testSetState() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        uiShopSection.setState(UIShopSection.ShopState.CLOSED);
        assertFalse(uiShopSection.isStarted());
        assertFalse(uiShopSection.isAwake());
        assertTrue(uiShopSection.isEnabled());
        assertEquals(UIShopSection.ShopState.CLOSED, uiShopSection.getLastState());
        assertEquals(UIShopSection.ShopState.MY_BUILDING_SELECTED, uiShopSection.getState());
    }

    @Test
    public void testSetState2() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        uiShopSection.setState(UIShopSection.ShopState.BUILDING_NEW);
        assertNull(uiShopSection.getCurrentPanel());
        assertEquals(UIShopSection.ShopState.BUILDING_NEW, uiShopSection.getLastState());
    }

    @Test
    public void testSetState3() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        uiShopSection.setState(UIShopSection.ShopState.ATTACK_SCREEN);
        assertNull(uiShopSection.getCurrentPanel());
        assertEquals(UIShopSection.ShopState.ATTACK_SCREEN, uiShopSection.getLastState());
    }

    @Test
    public void testSetState4() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        uiShopSection.setState(UIShopSection.ShopState.MY_BUILDING_SELECTED);
        assertNull(uiShopSection.getCurrentPanel());
        assertEquals(UIShopSection.ShopState.MY_BUILDING_SELECTED, uiShopSection.getLastState());
    }

    @Test
    public void testSetState5() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        uiShopSection.setCurrentPanel(new Reference<GameObject>(new GameObject("Name")));
        uiShopSection.setState(UIShopSection.ShopState.BUILDING_NEW);
        assertNull(uiShopSection.getCurrentPanel());
        assertEquals(UIShopSection.ShopState.BUILDING_NEW, uiShopSection.getLastState());
    }

    @Test
    public void testSetState6() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        uiShopSection.setLastState(UIShopSection.ShopState.BUILDING_NEW);
        uiShopSection.setState(UIShopSection.ShopState.CLOSED);
        assertNull(uiShopSection.getCurrentPanel());
        assertEquals(UIShopSection.ShopState.CLOSED, uiShopSection.getLastState());
    }

    @Test
    public void testSetState7() {
        UIShopSection uiShopSection =
                new UIShopSection(new UIMenuLeftDrawer(null, null, null, null, null, null));
        uiShopSection.setCurrentPanel(new Reference<GameObject>(new GameObject("Name")));
        uiShopSection.setLastState(UIShopSection.ShopState.BUILDING_NEW);
        uiShopSection.setState(UIShopSection.ShopState.CLOSED);
        assertNull(uiShopSection.getCurrentPanel());
        assertEquals(UIShopSection.ShopState.CLOSED, uiShopSection.getLastState());
    }
}
