/* (C) 2021 DragonSkulle */
package org.dragonskulle.renderer.components;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueLightTest {
    @Test
    public void testOnDestroy() {
        Light light = new Light();
        light.onDestroy();
        assertFalse(light.isStarted());
        assertEquals(Light.LightType.DIRECTIONAL, light.getLightType());
        assertEquals(10.0f, light.getIntensity(), 0.0f);
        assertFalse(light.isAwake());
        assertTrue(light.isEnabled());
    }
}
