/* (C) 2021 DragonSkulle */
package org.dragonskulle.audio.formats;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import java.io.UnsupportedEncodingException;
import java.nio.file.Paths;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueWaveSoundTest {
    @Test
    public void testLoadWave() {
        assertNull(
                WaveSound.loadWave(
                        Paths.get(System.getProperty("java.io.tmpdir"), "test.txt").toFile()));
    }

    @Test
    public void testConstructor() throws UnsupportedEncodingException {
        byte[] bytes = "AAAAAAAAAAAAAAAAAAAAAAAA".getBytes("UTF-8");
        new WaveSound(bytes);
        assertEquals(24, bytes.length);
    }

    @Test
    public void testConstructor2() throws UnsupportedEncodingException {
        byte[] bytes = "AAAAAAAA".getBytes("UTF-8");
        new WaveSound(bytes);
        assertEquals(8, bytes.length);
        assertArrayEquals("AAAAAAAA".getBytes("UTF-8"), bytes);
        assertEquals('A', bytes[0]);
        assertEquals('A', bytes[1]);
        assertEquals('A', bytes[2]);
        assertEquals('A', bytes[3]);
        assertEquals('A', bytes[4]);
        assertEquals('A', bytes[5]);
        assertEquals('A', bytes[6]);
        assertEquals('A', bytes[7]);
    }
}
