# This workflow will mirror the repo to Gitlab using secret tokens

name: Mirror to gitlab

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: ${{ secrets.GITLAB_REPO  }}
          PUSH_ALL_REFS: "true"

