/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.building;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueBuildingTest {
    @Test
    public void testSetStatsRequireVisualUpdate() {
        Building building = new Building();
        building.setStatsRequireVisualUpdate();
        assertEquals(1, building.getStatUpdateCount());
    }

    @Test
    public void testAfterStatChange() {
        Building building = new Building();
        building.setCapital(true);
        building.afterStatChange();
        assertEquals(1, building.getStatBaseCost());
        assertEquals(1, building.getStatUpdateCount());
        assertNull(building.getRandomAttackableBuilding());
    }

    @Test
    public void testOnClaimTile() {
        Building building = new Building();
        building.onClaimTile(null);
        assertNull(building.getRandomAttackableBuilding());
    }

    @Test
    public void testGetRandomAttackableBuilding() {
        assertNull((new Building()).getRandomAttackableBuilding());
    }

    @Test
    public void testIsBuildingAttackable() {
        Building building = new Building();
        assertFalse(building.isBuildingAttackable(new Building()));
    }

    @Test
    public void testGetAttackCost() {
        assertEquals(27, (new Building()).getAttackCost());
    }

    @Test
    public void testGetAttackCost2() {
        Building building = new Building();
        building.setCapital(true);
        assertEquals(37, building.getAttackCost());
    }
}
