/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.building;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.dragonskulle.audio.components.AudioListener;
import org.dragonskulle.core.GameObject;
import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlue {
    @Test
    public void testOnStart() {
        FogInvisibility fogInvisibility = new FogInvisibility();
        fogInvisibility.setGameObject(new GameObject("Name"));
        fogInvisibility.onStart();
    }

    @Test
    public void testOnStart2() {
        GameObject gameObject = new GameObject("Name");
        gameObject.addComponent(new AudioListener());

        FogInvisibility fogInvisibility = new FogInvisibility();
        fogInvisibility.setGameObject(gameObject);
        fogInvisibility.onStart();
    }

    @Test
    public void testOnStart3() {
        GameObject gameObject = new GameObject("Name");
        gameObject.addComponent(new Building());

        FogInvisibility fogInvisibility = new FogInvisibility();
        fogInvisibility.setGameObject(gameObject);
        fogInvisibility.onStart();
    }

    @Test
    public void testLateFrameUpdate() {
        FogInvisibility fogInvisibility = new FogInvisibility();
        fogInvisibility.lateFrameUpdate(0.5f);
        assertFalse(fogInvisibility.isStarted());
        assertTrue(fogInvisibility.isEnabled());
        assertFalse(fogInvisibility.isAwake());
    }

    @Test
    public void testOnDestroy() {
        FogInvisibility fogInvisibility = new FogInvisibility();
        fogInvisibility.onDestroy();
        assertFalse(fogInvisibility.isStarted());
        assertTrue(fogInvisibility.isEnabled());
        assertFalse(fogInvisibility.isAwake());
    }
}
