/* (C) 2021 DragonSkulle */
package org.dragonskulle.game.building;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

// The below tests were generated by https://www.diffblue.com/

public class DiffBlueBuildingMeshUpdaterTest {
    @Test
    public void testOnDestroy() {
        BuildingMeshUpdater buildingMeshUpdater = new BuildingMeshUpdater();
        buildingMeshUpdater.onDestroy();
        assertFalse(buildingMeshUpdater.isStarted());
        assertTrue(buildingMeshUpdater.isEnabled());
        assertFalse(buildingMeshUpdater.isAwake());
    }

    @Test
    public void testFrameUpdate() {
        BuildingMeshUpdater buildingMeshUpdater = new BuildingMeshUpdater();
        buildingMeshUpdater.frameUpdate(0.5f);
        assertFalse(buildingMeshUpdater.isStarted());
        assertTrue(buildingMeshUpdater.isEnabled());
        assertFalse(buildingMeshUpdater.isAwake());
    }
}
